

services:
  web:
    build: ./app
    ports:
      - "9090:5000"            # host 9090 → container 5000
    volumes:
      - ./app:/app             # live code mount
      - ./data:/data           # persist SQLite DB here
    env_file:
      - ./app/.env             # load API_KEY, API_SECRET, DB_PATH
